[Debug&Enhancement] (#3)
* [1] add hostname in error message; [2] refine comments and doc

[1] so we can know which worker node went wrong.

* [Debug] fix an error which makes the node failure-tolerant feature fails

It's a typo. But an extremely serious one

* [1] Move heartbeat function of worker node to top-level, instead of as a class method; [2] Lengthen the wait time in list_workers ; [3] clean code

[1] this function is put at top level rather than as a method of WorkerNode class. This is to bypass the error "AttributeError: type object 'ServerQueueManager' has no attribute 'from_address'""